# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               eldritchjs's mutterings
tagline:             'Notes from the journey'
description:         'This is my github pages blog. There are many like it, but this one is mine.'
url:                 http://eldritchjs.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Jason Schlessman
  url:               https://twitter.com/eldritchjs
  email:             jschless@redhat.com

# Custom vars
version:             1.0.0

gems: [jekyll-paginate]
